version = 1

exclude_patterns = [
  "frontend/eslint.config.js",
  "frontend/src/services/api/axiosClient.js",
  "frontend/src/services/api/_utils.js"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser", "es2022", "node"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
