// Major Indian cities for the new-pipeline city selector. Kept as a plain,
// alphabetically-sorted list so the dropdown stays readable; the backend does
// not constrain `city` (free text), so this is a UX convenience, not a
// validation source. The original seven markets are preserved verbatim so
// existing saved values stay consistent. Add to this list as new markets open.
export const INDIAN_CITIES = [
  'Agra',
  'Ahmedabad',
  'Ajmer',
  'Amritsar',
  'Aurangabad',
  'Bengaluru',
  'Bhopal',
  'Bhubaneswar',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Dehradun',
  'Faridabad',
  'Ghaziabad',
  'Goa',
  'Gurugram',
  'Guwahati',
  'Hyderabad',
  'Indore',
  'Jaipur',
  'Jalandhar',
  'Jammu',
  'Jamshedpur',
  'Jodhpur',
  'Kanpur',
  'Kochi',
  'Kolkata',
  'Kozhikode',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Mangaluru',
  'Meerut',
  'Mumbai',
  'Mysuru',
  'Nagpur',
  'Nashik',
  'Navi Mumbai',
  'New Delhi',
  'Noida',
  'Patna',
  'Puducherry',
  'Pune',
  'Raipur',
  'Rajkot',
  'Ranchi',
  'Surat',
  'Thane',
  'Thiruvananthapuram',
  'Tiruchirappalli',
  'Vadodara',
  'Varanasi',
  'Vijayawada',
  'Visakhapatnam',
];

export default INDIAN_CITIES;
