-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  plan text NOT NULL DEFAULT 'standard'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  seat_limit integer NOT NULL DEFAULT 10,
  workspace_code text NOT NULL,
  logo_url text,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'executive'::text CHECK (role = ANY (ARRAY['business_admin'::text, 'supervisor'::text, 'executive'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_city text,
  notes text,
  password_hash text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.sites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  submitted_by uuid NOT NULL,
  assigned_to uuid,
  supervisor_id uuid,
  name text NOT NULL,
  city text NOT NULL,
  address text,
  google_maps_pin text,
  visit_date date,
  model text,
  spoc_name text,
  spoc_phone text,
  spoc_email text,
  status text NOT NULL DEFAULT 'draft_submitted'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  draft_submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  shortlisted_at timestamp with time zone,
  details_submitted_at timestamp with time zone,
  approved_at timestamp with time zone,
  loi_uploaded_at timestamp with time zone,
  pushed_to_payments_at timestamp with time zone,
  rejected_at timestamp with time zone,
  archived_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  rejection_reason text,
  archive_note text,
  code text,
  expected_rent numeric,
  rent_type text CHECK ((rent_type = ANY (ARRAY['fixed'::text, 'revshare'::text, 'mg_revshare'::text])) OR rent_type IS NULL),
  rent_set_at timestamp with time zone,
  archived_from_status text,
  legal_review_at timestamp with time zone,
  legal_approved_at timestamp with time zone,
  legal_rejected_at timestamp with time zone,
  legal_dd_status text NOT NULL DEFAULT 'pending'::text CHECK (legal_dd_status = ANY (ARRAY['pending'::text, 'in_review'::text, 'positive'::text, 'negative'::text])),
  agreement_status text NOT NULL DEFAULT 'pending'::text CHECK (agreement_status = ANY (ARRAY['pending'::text, 'signed'::text, 'registered'::text])),
  licensing_status text NOT NULL DEFAULT 'pending'::text CHECK (licensing_status = ANY (ARRAY['pending'::text, 'partial'::text, 'complete'::text])),
  google_maps_url text,
  expected_escalation_pct numeric,
  expected_revshare_pct numeric,
  expected_escalation_years smallint,
  kyc_verified boolean NOT NULL DEFAULT false,
  ca_code text,
  finance_amount numeric,
  finance_status text NOT NULL DEFAULT 'pending'::text CHECK (finance_status = ANY (ARRAY['pending'::text, 'awaiting_supervisor'::text, 'awaiting_admin'::text, 'approved'::text])),
  design_status text NOT NULL DEFAULT 'pending'::text CHECK (design_status = ANY (ARRAY['pending'::text, 'allocated'::text, 'in_progress'::text, 'gfc_pending'::text, 'approved'::text, 'rejected'::text])),
  design_approved_at timestamp with time zone,
  project_status text NOT NULL DEFAULT 'pending'::text CHECK (project_status = ANY (ARRAY['pending'::text, 'allocated'::text, 'budgeting'::text, 'in_progress'::text, 'done'::text])),
  project_completed_at timestamp with time zone,
  is_launched boolean NOT NULL DEFAULT false,
  launched_at timestamp with time zone,
  project_excellence_status text NOT NULL DEFAULT 'pending'::text,
  financial_closure_status text NOT NULL DEFAULT 'pending'::text,
  CONSTRAINT sites_pkey PRIMARY KEY (id),
  CONSTRAINT sites_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sites_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.users(id),
  CONSTRAINT sites_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT sites_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.users(id)
);
CREATE TABLE public.site_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  site_id uuid NOT NULL UNIQUE,
  tenant_id uuid NOT NULL,
  carpet_area_sqft numeric,
  estimated_monthly_sales numeric,
  capex numeric,
  security_deposit numeric,
  cam_charges numeric,
  brokerage numeric,
  nearest_starbucks_m integer,
  nearest_twc_m integer,
  score numeric,
  rent_type text,
  fixed_rent_amt numeric,
  rev_share_pct numeric,
  escalation_pct numeric,
  rent_free_days integer,
  lock_in_months integer,
  tenure_months integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completion_pct integer DEFAULT ((((((((((
CASE
    WHEN (carpet_area_sqft IS NOT NULL) THEN 1
    ELSE 0
END +
CASE
    WHEN (estimated_monthly_sales IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (capex IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (security_deposit IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (score IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (rent_type IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (fixed_rent_amt IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (nearest_starbucks_m IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (lock_in_months IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (tenure_months IS NOT NULL) THEN 1
    ELSE 0
END) * 10),
  escalation_date date,
  CONSTRAINT site_details_pkey PRIMARY KEY (id),
  CONSTRAINT site_details_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT site_details_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.approvals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  site_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  approver_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  rejection_reason text,
  rejection_category text,
  notes text,
  expected_loi_days integer,
  loi_deadline date,
  decided_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT approvals_pkey PRIMARY KEY (id),
  CONSTRAINT approvals_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT approvals_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES public.users(id)
);
CREATE TABLE public.site_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  site_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  uploaded_by uuid NOT NULL,
  file_type text NOT NULL,
  file_name text NOT NULL,
  storage_path text NOT NULL,
  file_size_kb integer,
  mime_type text,
  source text NOT NULL DEFAULT 'manual_upload'::text,
  onedrive_item_id text,
  onedrive_synced_at timestamp with time zone,
  is_primary boolean DEFAULT false,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_files_pkey PRIMARY KEY (id),
  CONSTRAINT site_files_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT site_files_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT site_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.stage_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  site_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  actor_id uuid,
  event_type text NOT NULL,
  from_status text,
  to_status text,
  actor_role text,
  api_route text,
  source text DEFAULT 'web'::text,
  metadata jsonb,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT stage_events_pkey PRIMARY KEY (id),
  CONSTRAINT stage_events_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT stage_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT stage_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  actor_id uuid,
  entity_type text,
  entity_id uuid,
  action text NOT NULL,
  old_value jsonb,
  new_value jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  site_id uuid,
  actor_name text,
  from_status text,
  to_status text,
  field_name text,
  from_value text,
  to_value text,
  detail text,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id),
  CONSTRAINT audit_logs_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.notification_outbox (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid,
  site_id uuid,
  recipient_id uuid,
  type text NOT NULL,
  channel text NOT NULL DEFAULT 'email'::text CHECK (channel = ANY (ARRAY['email'::text, 'slack'::text, 'in_app'::text])),
  recipient_email text,
  subject text,
  body text,
  payload jsonb,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'skipped'::text])),
  attempts integer NOT NULL DEFAULT 0,
  sent_at timestamp with time zone,
  failed_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_outbox_pkey PRIMARY KEY (id),
  CONSTRAINT notification_outbox_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT notification_outbox_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT notification_outbox_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id)
);
CREATE TABLE public.workspace_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company text NOT NULL,
  admin_email text NOT NULL,
  team_size text,
  seat_limit integer NOT NULL DEFAULT 10,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::workspace_request_status,
  notes text,
  decided_at timestamp with time zone,
  decided_by uuid,
  provisioned_tenant_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  source_ip inet,
  CONSTRAINT workspace_requests_pkey PRIMARY KEY (id),
  CONSTRAINT workspace_requests_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES public.users(id),
  CONSTRAINT workspace_requests_provisioned_tenant_id_fkey FOREIGN KEY (provisioned_tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.shortlist_delegations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  site_id uuid NOT NULL,
  delegate_user_id uuid NOT NULL,
  granted_by uuid NOT NULL,
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  revoked_by uuid,
  notes text,
  CONSTRAINT shortlist_delegations_pkey PRIMARY KEY (id),
  CONSTRAINT shortlist_delegations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT shortlist_delegations_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT shortlist_delegations_delegate_user_id_fkey FOREIGN KEY (delegate_user_id) REFERENCES public.users(id),
  CONSTRAINT shortlist_delegations_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id),
  CONSTRAINT shortlist_delegations_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES public.users(id)
);
CREATE TABLE public.business_admins (
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  promoted_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  CONSTRAINT business_admins_pkey PRIMARY KEY (user_id),
  CONSTRAINT business_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT business_admins_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.module_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  module text NOT NULL CHECK (module = ANY (ARRAY['bd'::text, 'legal'::text, 'design'::text, 'project'::text, 'nso'::text, 'payment'::text, 'project_excellence'::text])),
  code text NOT NULL UNIQUE,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  rotated_at timestamp with time zone,
  revoked_at timestamp with time zone,
  CONSTRAINT module_codes_pkey PRIMARY KEY (id),
  CONSTRAINT module_codes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT module_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.supervisor_invite_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  supervisor_id uuid NOT NULL,
  module text NOT NULL CHECK (module = ANY (ARRAY['bd'::text, 'legal'::text, 'design'::text, 'project'::text, 'nso'::text, 'payment'::text, 'project_excellence'::text])),
  code text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  rotated_at timestamp with time zone,
  revoked_at timestamp with time zone,
  CONSTRAINT supervisor_invite_codes_pkey PRIMARY KEY (id),
  CONSTRAINT supervisor_invite_codes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT supervisor_invite_codes_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_module_memberships (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  module text NOT NULL CHECK (module = ANY (ARRAY['bd'::text, 'legal'::text, 'design'::text, 'project'::text, 'nso'::text, 'payment'::text, 'project_excellence'::text])),
  role_in_module text NOT NULL CHECK (role_in_module = ANY (ARRAY['supervisor'::text, 'executive'::text])),
  supervisor_id uuid,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_module_memberships_pkey PRIMARY KEY (id),
  CONSTRAINT user_module_memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT user_module_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_module_memberships_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.users(id)
);
CREATE TABLE public.legal_dd_checklist (
  site_id uuid NOT NULL,
  title_doc text NOT NULL DEFAULT 'pending'::text CHECK (title_doc = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  sanctioned_plan text NOT NULL DEFAULT 'pending'::text CHECK (sanctioned_plan = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  oc_cc text NOT NULL DEFAULT 'pending'::text CHECK (oc_cc = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  commercial_use text NOT NULL DEFAULT 'pending'::text CHECK (commercial_use = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  property_tax text NOT NULL DEFAULT 'pending'::text CHECK (property_tax = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  electricity text NOT NULL DEFAULT 'pending'::text CHECK (electricity = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  fire_noc text NOT NULL DEFAULT 'pending'::text CHECK (fire_noc = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  other_1 text NOT NULL DEFAULT 'pending'::text CHECK (other_1 = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  other_2 text NOT NULL DEFAULT 'pending'::text CHECK (other_2 = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  final_verdict text NOT NULL DEFAULT 'pending'::text CHECK (final_verdict = ANY (ARRAY['pending'::text, 'positive'::text, 'negative'::text])),
  rejection_reason text,
  reviewed_by uuid,
  approved_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stage text NOT NULL DEFAULT 'published'::text CHECK (stage = ANY (ARRAY['draft'::text, 'pending_review'::text, 'published'::text])),
  other_1_label text,
  other_2_label text,
  CONSTRAINT legal_dd_checklist_pkey PRIMARY KEY (site_id),
  CONSTRAINT legal_dd_checklist_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT legal_dd_checklist_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT legal_dd_checklist_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.site_agreement (
  site_id uuid NOT NULL,
  signed boolean NOT NULL DEFAULT false,
  signed_at timestamp with time zone,
  registered boolean NOT NULL DEFAULT false,
  registered_at timestamp with time zone,
  document_url text,
  CONSTRAINT site_agreement_pkey PRIMARY KEY (site_id),
  CONSTRAINT site_agreement_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.site_licensing (
  site_id uuid NOT NULL,
  fssai text NOT NULL DEFAULT 'pending'::text CHECK (fssai = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  health_trade text NOT NULL DEFAULT 'pending'::text CHECK (health_trade = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  shops_estab_reg text NOT NULL DEFAULT 'pending'::text CHECK (shops_estab_reg = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  fire_noc text NOT NULL DEFAULT 'pending'::text CHECK (fire_noc = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  storage_license text NOT NULL DEFAULT 'pending'::text CHECK (storage_license = ANY (ARRAY['pending'::text, 'yes'::text, 'no'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stage text NOT NULL DEFAULT 'published'::text CHECK (stage = ANY (ARRAY['draft'::text, 'pending_review'::text, 'published'::text])),
  CONSTRAINT site_licensing_pkey PRIMARY KEY (site_id),
  CONSTRAINT site_licensing_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.legal_change_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  site_id uuid NOT NULL,
  target_table text NOT NULL CHECK (target_table = ANY (ARRAY['legal_dd_checklist'::text, 'site_agreement'::text, 'site_licensing'::text])),
  field_name text NOT NULL,
  current_value text NOT NULL,
  requested_value text NOT NULL,
  justification text,
  requested_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewer_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_at timestamp with time zone,
  CONSTRAINT legal_change_requests_pkey PRIMARY KEY (id),
  CONSTRAINT legal_change_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT legal_change_requests_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT legal_change_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT legal_change_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.site_delegations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  site_id uuid NOT NULL,
  module text NOT NULL CHECK (module = ANY (ARRAY['bd'::text, 'legal'::text, 'design'::text, 'project'::text, 'nso'::text, 'project_excellence'::text, 'financial_closure'::text])),
  delegate_user_id uuid NOT NULL,
  granted_by uuid NOT NULL,
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  revoked_by uuid,
  notes text,
  CONSTRAINT site_delegations_pkey PRIMARY KEY (id),
  CONSTRAINT site_delegations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT site_delegations_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT site_delegations_delegate_user_id_fkey FOREIGN KEY (delegate_user_id) REFERENCES public.users(id),
  CONSTRAINT site_delegations_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id),
  CONSTRAINT site_delegations_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES public.users(id)
);
CREATE TABLE public.design_reviews (
  site_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  current_stage text NOT NULL DEFAULT 'recce'::text CHECK (current_stage = ANY (ARRAY['recce'::text, '2d'::text, '3d'::text, 'boq'::text, 'gfc'::text, 'done'::text])),
  gfc_status text NOT NULL DEFAULT 'pending'::text CHECK (gfc_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  gfc_comments text,
  gfc_decided_by uuid,
  gfc_decided_at timestamp with time zone,
  reviewed_by uuid,
  approved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT design_reviews_pkey PRIMARY KEY (site_id),
  CONSTRAINT design_reviews_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT design_reviews_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT design_reviews_gfc_decided_by_fkey FOREIGN KEY (gfc_decided_by) REFERENCES public.users(id),
  CONSTRAINT design_reviews_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT design_reviews_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.design_deliverables (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  site_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['recce'::text, '2d'::text, '3d'::text, 'boq'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'submitted'::text, 'approved'::text, 'rejected'::text])),
  file_url text,
  file_name text,
  estimated_amount numeric,
  supervisor_comments text,
  submitted_by uuid,
  submitted_at timestamp with time zone,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  admin_status text NOT NULL DEFAULT 'pending'::text CHECK (admin_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  admin_comments text,
  admin_reviewed_by uuid,
  admin_reviewed_at timestamp with time zone,
  CONSTRAINT design_deliverables_pkey PRIMARY KEY (id),
  CONSTRAINT design_deliverables_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT design_deliverables_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT design_deliverables_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.users(id),
  CONSTRAINT design_deliverables_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT design_deliverables_admin_reviewed_by_fkey FOREIGN KEY (admin_reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.project_reviews (
  site_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  project_status text NOT NULL DEFAULT 'pending'::text CHECK (project_status = ANY (ARRAY['pending'::text, 'allocated'::text, 'budgeting'::text, 'in_progress'::text, 'done'::text])),
  current_stage text NOT NULL DEFAULT 'execution'::text CHECK (current_stage = ANY (ARRAY['execution'::text, 'done'::text])),
  allocated_to uuid,
  initialization_date date,
  initialization_status text NOT NULL DEFAULT 'pending'::text CHECK (initialization_status = ANY (ARRAY['pending'::text, 'proposed'::text, 'submitted'::text, 'approved'::text, 'rejected'::text])),
  initialization_comments text,
  expected_completion_date date,
  expected_completion_status text NOT NULL DEFAULT 'pending'::text CHECK (expected_completion_status = ANY (ARRAY['pending'::text, 'submitted'::text, 'approved'::text, 'rejected'::text])),
  expected_completion_comments text,
  inspection_date date,
  quality_audit_status text NOT NULL DEFAULT 'pending'::text CHECK (quality_audit_status = ANY (ARRAY['pending'::text, 'submitted'::text, 'supervisor_approved'::text, 'approved'::text, 'rejected'::text])),
  quality_audit_comments text,
  final_completion_date date,
  project_completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  mid_project_visit_date date,
  nso_status text NOT NULL DEFAULT 'pending'::text CHECK (nso_status = ANY (ARRAY['pending'::text, 'pushed'::text])),
  pushed_to_nso_at timestamp with time zone,
  quality_audit_supervisor_approved_at timestamp with time zone,
  quality_audit_supervisor_approved_by uuid,
  quality_audit_admin_confirmed_at timestamp with time zone,
  quality_audit_admin_confirmed_by uuid,
  quality_audit_admin_notes text,
  CONSTRAINT project_reviews_pkey PRIMARY KEY (site_id),
  CONSTRAINT project_reviews_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT project_reviews_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT project_reviews_allocated_to_fkey FOREIGN KEY (allocated_to) REFERENCES public.users(id),
  CONSTRAINT project_reviews_quality_audit_supervisor_approved_by_fkey FOREIGN KEY (quality_audit_supervisor_approved_by) REFERENCES public.users(id),
  CONSTRAINT project_reviews_quality_audit_admin_confirmed_by_fkey FOREIGN KEY (quality_audit_admin_confirmed_by) REFERENCES public.users(id)
);
CREATE TABLE public.password_reset_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  email text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'completed'::text, 'rejected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_at timestamp with time zone,
  completed_at timestamp with time zone,
  reset_token_hash text,
  token_expires_at timestamp with time zone,
  CONSTRAINT password_reset_requests_pkey PRIMARY KEY (id),
  CONSTRAINT password_reset_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT password_reset_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.nso_reviews (
  site_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  current_stage text NOT NULL DEFAULT 'stage_one'::text CHECK (current_stage = ANY (ARRAY['stage_one'::text, 'stage_two'::text, 'stage_three'::text, 'final'::text, 'done'::text])),
  nso_status text NOT NULL DEFAULT 'pending'::text CHECK (nso_status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'complete'::text])),
  property_details text,
  communication_floated boolean,
  fssai_status text NOT NULL DEFAULT 'pending'::text CHECK (fssai_status = ANY (ARRAY['pending'::text, 'done'::text])),
  health_trade_status text NOT NULL DEFAULT 'pending'::text CHECK (health_trade_status = ANY (ARRAY['pending'::text, 'done'::text])),
  shops_estab_status text NOT NULL DEFAULT 'pending'::text CHECK (shops_estab_status = ANY (ARRAY['pending'::text, 'done'::text])),
  fire_noc_status text NOT NULL DEFAULT 'pending'::text CHECK (fire_noc_status = ANY (ARRAY['pending'::text, 'done'::text])),
  storage_license_status text NOT NULL DEFAULT 'pending'::text CHECK (storage_license_status = ANY (ARRAY['pending'::text, 'done'::text])),
  dry_stock_order_status text NOT NULL DEFAULT 'pending'::text CHECK (dry_stock_order_status = ANY (ARRAY['pending'::text, 'ordered'::text, 'received'::text])),
  online_delivery_status text NOT NULL DEFAULT 'pending'::text CHECK (online_delivery_status = ANY (ARRAY['pending'::text, 'ready'::text, 'active'::text])),
  handover_checklist_signed boolean,
  launch_date date,
  launch_ready boolean,
  final_approval_signoff_1 boolean NOT NULL DEFAULT false,
  final_approval_signoff_2 boolean NOT NULL DEFAULT false,
  stage_one_completed_at timestamp with time zone,
  stage_two_completed_at timestamp with time zone,
  stage_three_completed_at timestamp with time zone,
  final_approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  handover_pushed_at timestamp with time zone,
  CONSTRAINT nso_reviews_pkey PRIMARY KEY (site_id),
  CONSTRAINT nso_reviews_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT nso_reviews_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.launch_approvals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  site_id uuid NOT NULL UNIQUE,
  tenant_id uuid NOT NULL,
  rent_type text,
  fixed_rent_amt numeric,
  expected_rent numeric,
  rev_share_pct numeric,
  escalation_pct numeric,
  escalation_date date,
  expected_escalation_years integer,
  cam_charges numeric,
  security_deposit numeric,
  brokerage numeric,
  lock_in_months integer,
  tenure_months integer,
  rent_free_days integer,
  carpet_area_sqft numeric,
  estimated_monthly_sales numeric,
  capex numeric,
  score numeric,
  notes text,
  status text NOT NULL DEFAULT 'pending_admin_review'::text CHECK (status = ANY (ARRAY['pending_admin_review'::text, 'under_exec_review'::text, 'under_supervisor_review'::text, 'pending_admin_final'::text, 'ready_to_launch'::text, 'launched'::text])),
  admin_approved_at timestamp with time zone,
  admin_approved_by uuid,
  bd_confirmed_at timestamp with time zone,
  bd_confirmed_by uuid,
  supervisor_approved_at timestamp with time zone,
  supervisor_approved_by uuid,
  super_admin_approved_at timestamp with time zone,
  super_admin_approved_by uuid,
  launched_at timestamp with time zone,
  launched_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  admin_review_comment text,
  admin_sent_for_review_at timestamp with time zone,
  admin_sent_for_review_by uuid,
  exec_verdict text CHECK (exec_verdict IS NULL OR (exec_verdict = ANY (ARRAY['approved'::text, 'rejected'::text]))),
  exec_comment text,
  exec_reviewed_at timestamp with time zone,
  exec_reviewed_by uuid,
  supervisor_verdict text CHECK (supervisor_verdict IS NULL OR (supervisor_verdict = ANY (ARRAY['approved'::text, 'rejected'::text]))),
  supervisor_comment text,
  supervisor_reviewed_at timestamp with time zone,
  supervisor_reviewed_by uuid,
  admin_final_comment text,
  admin_confirmed_at timestamp with time zone,
  admin_confirmed_by uuid,
  committed_at timestamp with time zone,
  CONSTRAINT launch_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT launch_approvals_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT launch_approvals_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenents(id),
  CONSTRAINT launch_approvals_admin_approved_by_fkey FOREIGN KEY (admin_approved_by) REFERENCES public.users(id),
  CONSTRAINT launch_approvals_bd_confirmed_by_fkey FOREIGN KEY (bd_confirmed_by) REFERENCES public.users(id),
  CONSTRAINT launch_approvals_supervisor_approved_by_fkey FOREIGN KEY (supervisor_approved_by) REFERENCES public.users(id),
  CONSTRAINT launch_approvals_super_admin_approved_by_fkey FOREIGN KEY (super_admin_approved_by) REFERENCES public.users(id),
  CONSTRAINT launch_approvals_launched_by_fkey FOREIGN KEY (launched_by) REFERENCES public.users(id),
  CONSTRAINT launch_approvals_admin_sent_for_review_by_fkey FOREIGN KEY (admin_sent_for_review_by) REFERENCES public.users(id),
  CONSTRAINT launch_approvals_exec_reviewed_by_fkey FOREIGN KEY (exec_reviewed_by) REFERENCES public.users(id),
  CONSTRAINT launch_approvals_supervisor_reviewed_by_fkey FOREIGN KEY (supervisor_reviewed_by) REFERENCES public.users(id),
  CONSTRAINT launch_approvals_admin_confirmed_by_fkey FOREIGN KEY (admin_confirmed_by) REFERENCES public.users(id)
);
CREATE TABLE public.launch_review_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  launch_approval_id uuid NOT NULL,
  site_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  actor_id uuid,
  actor_name text,
  actor_role text,
  stage text NOT NULL,
  action text NOT NULL,
  comment text,
  changes jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT launch_review_events_pkey PRIMARY KEY (id),
  CONSTRAINT launch_review_events_launch_approval_id_fkey FOREIGN KEY (launch_approval_id) REFERENCES public.launch_approvals(id),
  CONSTRAINT launch_review_events_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT launch_review_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT launch_review_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.site_budgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  site_id uuid NOT NULL,
  phase text NOT NULL CHECK (phase = ANY (ARRAY['gfc'::text, 'closure'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_supervisor'::text, 'pending_admin'::text, 'approved'::text, 'rejected'::text])),
  allocated_to uuid,
  budget_total numeric,
  total_indoor_area_sqft numeric,
  total_area_sqft numeric,
  covers integer,
  supervisor_comments text,
  admin_comments text,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_budgets_pkey PRIMARY KEY (id),
  CONSTRAINT site_budgets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT site_budgets_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT site_budgets_allocated_to_fkey FOREIGN KEY (allocated_to) REFERENCES public.users(id)
);
CREATE TABLE public.site_budget_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  site_id uuid NOT NULL,
  budget_id uuid NOT NULL,
  phase text NOT NULL CHECK (phase = ANY (ARRAY['gfc'::text, 'closure'::text])),
  idx integer NOT NULL CHECK (idx >= 1 AND idx <= 11),
  label text,
  amount numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_budget_items_pkey PRIMARY KEY (id),
  CONSTRAINT site_budget_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT site_budget_items_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT site_budget_items_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES public.site_budgets(id)
);
